# Generated by Django 4.2.6 on 2023-11-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TDMS", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="formatted_address",
            new_name="address",
        ),
    ]
