# Generated by Django 4.2.6 on 2023-11-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TDMS", "0002_rename_formatted_address_location_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="long",
            new_name="lng",
        ),
        migrations.RemoveField(
            model_name="location",
            name="place_id",
        ),
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
