# Generated by Django 4.2.6 on 2023-11-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TDMS", "0003_rename_long_location_lng_remove_location_place_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
