# Generated by Django 4.2.6 on 2023-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDMS', '0007_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='waypoints',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
