# Generated by Django 4.2.6 on 2023-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDMS', '0008_plan_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
