# Generated by Django 4.2.6 on 2023-11-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDMS', '0010_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('crt', 'Created'), ('upd', 'Updated'), ('del', 'Deleted'), ('lgn', 'Logged In'), ('lgt', 'Logged Out'), ('non', 'None')], default='non', max_length=3),
        ),
    ]
