# Generated by Django 4.2.6 on 2023-11-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDMS', '0011_alter_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='field_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='new_value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='old_value',
            field=models.TextField(null=True),
        ),
    ]
