# Generated by Django 4.2.6 on 2023-11-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TDMS', '0012_log_field_name_log_new_value_log_old_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='waypoints',
        ),
    ]
