# Generated by Django 4.2.6 on 2023-12-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDMS', '0013_remove_plan_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=60, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='account',
            name='ssn',
            field=models.CharField(default=111, max_length=9, unique=True, verbose_name='ssn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
    ]
